---
- name: Get all packages
  package_facts:
    manager: auto

- name: Check if firewall package is installed
  set_fact:
    firewall_installed: "{{ 'firewalld' in ansible_facts.packages }}"

- name: Checking if firewalld is running and enabled
  command: "{{ item }}"
  register: service_state
  loop:
    - systemctl is-active firewalld
    - systemctl is-enabled firewalld
