---
- name: Check the current pam comfiguration
  set_fact:
    pam_config_status: "{{ 'PASS' if curr_conf.rc == 0 else 'FAIL' }}"

- name: Extracting the current pwquality config
  set_fact:
    pw_quality_conf_values: >-
      {{
        pw_quality_conf_values | default({}) |
        combine({
          item.key:
          (
            pwquality_out.stdout | regex_findall(item.regex) |
            first
          )
        })
      }}
  loop:
    - { key: "minlen", regex: '(?im)^minlen\s*=\s*(\S+)' }
    - { key: "dcredit", regex: '(?im)^dcredit\s*=\s*(\S+)' }
    - { key: "ucredit", regex: '(?im)^ucredit\s*=\s*(\S+)' }
    - { key: "lcredit", regex: '(?im)^lcredit\s*=\s*(\S+)' }
    - { key: "ocredit", regex: '(?im)^ocredit\s*=\s*(\S+)' }
    - { key: "minclass", regex: '(?im)^minclass\s*=\s*(\S+)' }

- name: Extracting the current faillock config
  set_fact:
    faillock_conf_values: >-
      {{
        faillock_conf_values | default({}) |
        combine({
          item.key:
          (
            faillock_out.stdout | regex_findall(item.regex) |
            first
          )
        })
      }}
  loop:
    - { key: "deny", regex: '(?im)^deny\s*=\s*(\S+)' }
    - { key: "fail_interval", regex: '(?im)^fail_interval\s*=\s*(\S+)' }
    - { key: "unlock_time", regex: '(?im)^unlock_time\s*=\s*(\S+)' }
    - { key: "root_unlock_time", regex: '(?im)^root_unlock_time\s*=\s*(\S+)' }

- name: Extracting the current logindefs
  set_fact:
    logindef_values: >-
      {{
        logindef_values | default({}) |
        combine({
          item.key:
          (
            logindef_out.stdout | regex_findall(item.regex) |
            first
          )
        })
      }}
  loop:
    - { key: "PASS_MIN_DAYS", regex: '(?im)^PASS_MIN_DAYS\s+(\S+)' }
    - { key: "PASS_MAX_DAYS", regex: '(?im)^PASS_MAX_DAYS\s+(\S+)' }
    - { key: "PASS_WARN_AGE", regex: '(?im)^PASS_WARN_AGE\s+(\S+)' }
    - { key: "PASS_MIN_LEN", regex: '(?im)^PASS_MIN_LEN\s+(\S+)' }

- name: Checking if parameters are correctly
  set_fact:
    validation: >-
      {{
        validation | default({}) |
        combine({
          item.name:
          (
            'PASS' if (item.current|string) == (item.expected|string) else 'FAIL'
          )
        })
      }}
  loop:
    - name: "minlen"
      current: "{{ pw_quality_conf_values.minlen }}"
      expected: "{{ password_min_length }}"
    - name: "dcredit"
      current: "{{ pw_quality_conf_values.dcredit }}"
      expected: "{{ min_num_digit }}"
    - name: "ucredit"
      current: "{{ pw_quality_conf_values.ucredit }}"
      expected: "{{ min_upper_case }}"
    - name: "lcredit"
      current: "{{ pw_quality_conf_values.lcredit }}"
      expected: "{{ min_lower_case }}"
    - name: "ocredit"
      current: "{{ pw_quality_conf_values.ocredit }}"
      expected: "{{ min_oth_char }}"
    - name: "minclass"
      current: "{{ pw_quality_conf_values.minclass }}"
      expected: "{{ min_num_class }}"
    - name: "deny"
      current: "{{ faillock_conf_values.deny }}"
      expected: "{{ brute_force_num }}"
    - name: "time_within_check"
      current: "{{ faillock_conf_values.fail_interval }}"
      expected: "{{ time_within_check }}"
    - name: "time_to_unlock"
      current: "{{ faillock_conf_values.unlock_time }}"
      expected: "{{ time_to_unlock }}"
    - name: "time_to_unlock_root"
      current: "{{ faillock_conf_values.root_unlock_time }}"
      expected: "{{ time_to_unlock_root }}"
    - name: "password_min_days"
      current: "{{ logindef_values.PASS_MIN_DAYS }}"
      expected: "{{ password_min_days }}"
    - name: "password_max_days"
      current: "{{ logindef_values.PASS_MAX_DAYS }}"
      expected: "{{ password_max_days }}"
    - name: "password_warn_age"
      current: "{{ logindef_values.PASS_WARN_AGE }}"
      expected: "{{ password_warn_days }}"
    - name: "password_min_len"
      current: "{{ logindef_values.PASS_MIN_LEN }}"
      expected: "{{ password_min_length }}"

- name: Generate the pwcomplexity report
  template:
    src: pwcomplex_compliance_report.j2
    dest: /reports/pwcomplexity_reports/{{ inventory_hostname }}_{{ ansible_date_time.date }}
    mode: 0644
    owner: root
    group: root
  delegate_to: localhost
