password_min_length: '12'
min_num_digit: '-1'
min_upper_case: '-1'
min_lower_case: '-1'
min_oth_char: '-1'
min_num_class: '4'
brute_force_num: '3'
time_within_check: '900'
time_to_unlock: '600'
time_to_unlock_root: '600'
password_min_days: '2'
password_max_days: '90'
password_warn_days: '15'
